#include "./types.h"
#include "./wrapper/wrapper.h"

// enum values expected to be generated by the compiler
u32 JS_Json_run;
u32 JS_Json_runOnString;

static void* eval_run(void* args[]) {
  return Wrapper_callJsSync(JS_Json_run, 2, args);
}
Closure Json_run = {
    .header = HEADER_CLOSURE(0),
    .max_values = 2,
    .evaluator = &eval_run,
};

static void* eval_runOnString(void* args[]) {
  return Wrapper_callJsSync(JS_Json_runOnString, 2, args);
}
Closure Json_runOnString = {
    .header = HEADER_CLOSURE(0),
    .max_values = 2,
    .evaluator = &eval_runOnString,
};
