/**
 * The Wasm side of the interface
 */
interface ElmWasmExports {
  getUnit: () => number;
  getNil: () => number;
  getTrue: () => number;
  getFalse: () => number;
  getNextFieldGroup: () => number;
  writeFloat: (addr: number, value: number) => void;
  readFloat: (addr: number) => number;
  getWriteAddr: () => number;
  getMaxWriteAddr: () => number;
  startWrite: () => number;
  finishedWritingAt: (addr: number) => void;
  callClosure: (addr: number) => number;
  collectGarbage: () => void;
}

/**
 * App-specific values generated by the Elm compiler
 */
interface ElmWasmAppTypes {
  ctors: NameToInt & IntToName; // compile time
  fields: NameToInt & IntToName; // compile time
  fieldGroupNames: string[]; // compile time
  fieldGroups: NameToInt & IntToName; // runtime (app init)
}

interface NameToInt {
  [name: string]: number;
}
interface IntToName {
  [int: number]: string;
}
