name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v6
      with:
        # Version to install
        version: '1.38.48' # optional, default is latest
        # If true will not download any version of Emscripten. emsdk will still be added to PATH.
        #no-install: # optional
        # If true will not cache any downloads with tc.cacheDir.
        #no-cache: # optional
        # Directory to cache emsdk in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cahce.
        actions-cache-folder: 'emsdk-cache'
        # Update tags before installing a version
        #update-tags: # optional
    - name: Build native
      run: make
    - name: Test native
      run: make check-bin
    - name: Build Wasm
      run: make wasm
    - name: Archive Emscripten test JS
      uses: actions/upload-artifact@v1
      with:
        name: emscripten-test-js
        path: dist/wasm/test.js
    - name: Test Wasm
      run: make check-node
