name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v5
      with:
        # Version to install
        version: '1.38.12' # optional, default is latest
        # If true will not download any version of Emscripten. emsdk will still be added to PATH.
        #no-install: # optional
        # If true will not cache any downloads with tc.cacheDir.
        #no-cache: # optional
        # Directory to cache emsdk in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cahce.
        #actions-cache-folder: # optional, default is 
        # Update tags before installing a version
        #update-tags: # optional
    - name: Native & Wasm tests
      run: emcc --version && make check
